{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🚀 Анализ данных о продажах\n",
    "## Работа с объединенным файлом merged_sales_data.csv"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Импорт библиотек и настройка"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from datetime import datetime\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Визуализация\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "# Настройки отображения\n",
    "pd.set_option('display.max_columns', None)\n",
    "pd.set_option('display.max_rows', 100)\n",
    "plt.style.use('seaborn-v0_8')\n",
    "sns.set_palette(\"husl\")\n",
    "\n",
    "print(\"✅ Библиотеки загружены\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Загрузка объединенного CSV файла"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_merged_data():\n",
    "    \"\"\"Загрузка объединенного CSV файла\"\"\"\n",
    "    \n",
    "    csv_file = 'merged_sales_data.csv'\n",
    "    \n",
    "    try:\n",
    "        df = pd.read_csv(csv_file, encoding='utf-8')\n",
    "        print(f\"✅ Файл {csv_file} успешно загружен\")\n",
    "        print(f\"📊 Размер данных: {df.shape}\")\n",
    "        return df\n",
    "        \n",
    "    except FileNotFoundError:\n",
    "        print(f\"❌ Файл {csv_file} не найден\")\n",
    "        print(\"📁 Убедитесь, что файл находится в текущей директории\")\n",
    "        return None\n",
    "    except Exception as e:\n",
    "        print(f\"❌ Ошибка загрузки: {e}\")\n",
    "        return None\n",
    "\n",
    "# Загружаем данные\n",
    "df = load_merged_data()\n",
    "\n",
    "if df is not None:\n",
    "    print(\"\\n👀 Первые 3 строки данных:\")\n",
    "    display(df.head(3))\n",
    "    \n",
    "    print(\"\\n📋 Информация о данных:\")\n",
    "    print(df.info())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Очистка и преобразование данных"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def clean_and_transform_data(df):\n",
    "    \"\"\"Очистка и преобразование данных\"\"\"\n",
    "    \n",
    "    print(\"🧹 ОЧИСТКА И ПРЕОБРАЗОВАНИЕ ДАННЫХ\")\n",
    "    print(\"=\" * 50)\n",
    "    \n",
    "    # Сохраняем исходный размер\n",
    "    initial_count = len(df)\n",
    "    print(f\"📊 Исходное количество строк: {initial_count}\")\n",
    "    \n",
    "    # Удаление дубликатов\n",
    "    df = df.drop_duplicates()\n",
    "    print(f\"📊 Удалено дубликатов: {initial_count - len(df)}\")\n",
    "    \n",
    "    # Анализ пропущенных значений\n",
    "    print(\"\\n📊 АНАЛИЗ ПРОПУЩЕННЫХ ЗНАЧЕНИЙ:\")\n",
    "    missing_data = df.isnull().sum()\n",
    "    missing_percent = (missing_data / len(df)) * 100\n",
    "    \n",
    "    missing_info = pd.DataFrame({\n",
    "        'Количество': missing_data,\n",
    "        'Процент': missing_percent\n",
    "    }).sort_values('Количество', ascending=False)\n",
    "    \n",
    "    # Показываем только колонки с пропусками\n",
    "    missing_columns = missing_info[missing_info['Количество'] > 0]\n",
    "    if len(missing_columns) > 0:\n",
    "        display(missing_columns.head(10))\n",
    "    else:\n",
    "        print(\"   Пропущенных значений не обнаружено\")\n",
    "    \n",
    "    # Заполнение пропусков для ключевых колонок\n",
    "    print(\"\\n🔧 ЗАПОЛНЕНИЕ ПРОПУСКОВ:\")\n",
    "    \n",
    "    if 'Color' in df.columns:\n",
    "        df['Color'] = df['Color'].fillna('Not Specified')\n",
    "        print(\"   ✅ Color: заполнены пропуски\")\n",
    "    \n",
    "    if 'SubCategory' in df.columns:\n",
    "        df['SubCategory'] = df['SubCategory'].fillna('Unknown')\n",
    "        df['Category'] = df['Category'].fillna('Unknown')\n",
    "        print(\"   ✅ Category/SubCategory: заполнены пропуски\")\n",
    "    \n",
    "    # Для числовых колонок заполняем медианой\n",
    "    numeric_columns = df.select_dtypes(include=[np.number]).columns\n",
    "    for col in numeric_columns:\n",
    "        if df[col].isnull().sum() > 0:\n",
    "            df[col] = df[col].fillna(df[col].median())\n",
    "            print(f\"   ✅ {col}: заполнены пропуски медианой\")\n",
    "    \n",
    "    # Преобразование типов данных\n",
    "    print(\"\\n🔄 ПРЕОБРАЗОВАНИЕ ТИПОВ ДАННЫХ:\")\n",
    "    \n",
    "    date_columns = ['OrderDate', 'ShipDate', 'BirthDate', 'DateFirstPurchase', 'StartDate']\n",
    "    \n",
    "    for col in date_columns:\n",
    "        if col in df.columns:\n",
    "            df[col] = pd.to_datetime(df[col], errors='coerce')\n",
    "            print(f\"   🕐 {col}: преобразована в datetime\")\n",
    "    \n",
    "    # Создание новых признаков\n",
    "    print(\"\\n🎯 СОЗДАНИЕ НОВЫХ ПРИЗНАКОВ:\")\n",
    "    \n",
    "    if 'OrderDate' in df.columns:\n",
    "        df['OrderYear'] = df['OrderDate'].dt.year\n",
    "        df['OrderMonth'] = df['OrderDate'].dt.month\n",
    "        df['OrderQuarter'] = df['OrderDate'].dt.quarter\n",
    "        df['OrderDayOfWeek'] = df['OrderDate'].dt.day_name()\n",
    "        print(\"   📅 Созданы временные признаки из OrderDate\")\n",
    "        \n",
    "        # Расчет времени доставки\n",
    "        if 'ShipDate' in df.columns:\n",
    "            df['DeliveryDays'] = (df['ShipDate'] - df['OrderDate']).dt.days\n",
    "            print(\"   🚚 Создан признак DeliveryDays\")\n",
    "    \n",
    "    # Создание демографических сегментов\n",
    "    if 'YearlyIncome' in df.columns:\n",
    "        df['IncomeSegment'] = pd.cut(df['YearlyIncome'], \n",
    "                                   bins=[0, 50000, 80000, 100000, float('inf')],\n",
    "                                   labels=['Low', 'Medium', 'High', 'Very High'])\n",
    "        print(\"   💰 Создан IncomeSegment\")\n",
    "    \n",
    "    # Расчет возраста клиента\n",
    "    if 'BirthDate' in df.columns:\n",
    "        df['Age'] = (datetime.now() - df['BirthDate']).dt.days // 365\n",
    "        print(\"   👤 Создан Age\")\n",
    "    \n",
    "    # Расчет прибыльности\n",
    "    if 'SalesAmount' in df.columns and 'TotalProductCost' in df.columns:\n",
    "        df['Profit'] = df['SalesAmount'] - df['TotalProductCost']\n",
    "        df['ProfitMargin'] = (df['Profit'] / df['SalesAmount']) * 100\n",
    "        print(\"   💵 Созданы Profit и ProfitMargin\")\n",
    "    \n",
    "    # Расчет общей суммы, если нет\n",
    "    if 'UnitPrice' in df.columns and 'OrderQuantity' in df.columns and 'TotalAmount' not in df.columns:\n",
    "        df['TotalAmount'] = df['UnitPrice'] * df['OrderQuantity']\n",
    "        print(\"   📊 Создан TotalAmount\")\n",
    "    \n",
    "    print(f\"\\n✅ Очистка завершена! Финальный размер: {df.shape}\")\n",
    "    return df\n",
    "\n",
    "# Применяем очистку\n",
    "if df is not None:\n",
    "    cleaned_df = clean_and_transform_data(df)\n",
    "else:\n",
    "    cleaned_df = None"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Исследовательский анализ данных (EDA)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def perform_eda(df):\n",
    "    \"\"\"Исследовательский анализ данных\"\"\"\n",
    "    \n",
    "    print(\"🔍 ИССЛЕДОВАТЕЛЬСКИЙ АНАЛИЗ ДАННЫХ\")\n",
    "    print(\"=\" * 50)\n",
    "    \n",
    "    # Базовая статистика числовых колонок\n",
    "    numeric_cols = df.select_dtypes(include=[np.number]).columns\n",
    "    print(\"📈 ОСНОВНАЯ СТАТИСТИКА (числовые колонки):\")\n",
    "    display(df[numeric_cols].describe())\n",
    "    \n",
    "    # Анализ категориальных переменных\n",
    "    categorical_cols = df.select_dtypes(include=['object']).columns\n",
    "    print(f\"\\n📊 КАТЕГОРИАЛЬНЫЕ ПЕРЕМЕННЫЕ ({len(categorical_cols)}):\")\n",
    "    \n",
    "    for col in categorical_cols[:8]:  # Показываем первые 8\n",
    "        unique_count = df[col].nunique()\n",
    "        print(f\"   {col}: {unique_count} уникальных значений\")\n",
    "        if unique_count <= 10:\n",
    "            value_counts = df[col].value_counts()\n",
    "            print(f\"      Распределение: {dict(value_counts)}\")\n",
    "    \n",
    "    return df\n",
    "\n",
    "if cleaned_df is not None:\n",
    "    explored_df = perform_eda(cleaned_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Визуализации для EDA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_eda_visualizations(df):\n",
    "    \"\"\"Создание визуализаций для EDA\"\"\"\n",
    "    \n",
    "    print(\"📊 СОЗДАНИЕ ВИЗУАЛИЗАЦИЙ ДЛЯ EDA\")\n",
    "    \n",
    "    # Создаем subplots\n",
    "    fig, axes = plt.subplots(2, 3, figsize=(18, 12))\n",
    "    \n",
    "    # 1. Динамика продаж по времени\n",
    "    if 'OrderDate' in df.columns and 'SalesAmount' in df.columns:\n",
    "        monthly_sales = df.groupby(df['OrderDate'].dt.to_period('M'))['SalesAmount'].sum()\n",
    "        axes[0,0].plot(monthly_sales.index.astype(str), monthly_sales.values, \n",
    "                      marker='o', linewidth=2, color='blue')\n",
    "        axes[0,0].set_title('Динамика продаж по месяцам', fontsize=14, fontweight='bold')\n",
    "        axes[0,0].set_xlabel('Месяц')\n",
    "        axes[0,0].set_ylabel('Выручка (SalesAmount)')\n",
    "        axes[0,0].tick_params(axis='x', rotation=45)\n",
    "        axes[0,0].grid(True, alpha=0.3)\n",
    "    \n",
    "    # 2. Распределение по регионам\n",
    "    if 'Region' in df.columns:\n",
    "        region_sales = df.groupby('Region')['SalesAmount'].sum().sort_values(ascending=False)\n",
    "        axes[0,1].bar(range(len(region_sales)), region_sales.values, color='green', alpha=0.7)\n",
    "        axes[0,1].set_title('Выручка по регионам', fontsize=14, fontweight='bold')\n",
    "        axes[0,1].set_xlabel('Регион')\n",
    "        axes[0,1].set_ylabel('Выручка')\n",
    "        axes[0,1].set_xticks(range(len(region_sales)))\n",
    "        axes[0,1].set_xticklabels(region_sales.index, rotation=45)\n",
    "    \n",
    "    # 3. Распределение по категориям продуктов\n",
    "    if 'Category' in df.columns:\n",
    "        category_sales = df.groupby('Category')['SalesAmount'].sum()\n",
    "        axes[0,2].pie(category_sales.values, labels=category_sales.index, \n",
    "                     autopct='%1.1f%%', startangle=90)\n",
    "        axes[0,2].set_title('Распределение выручки по категориям', fontsize=14, fontweight='bold')\n",
    "    \n",
    "    # 4. Распределение доходов клиентов\n",
    "    if 'YearlyIncome' in df.columns:\n",
    "        axes[1,0].hist(df['YearlyIncome'], bins=20, alpha=0.7, edgecolor='black', color='orange')\n",
    "        axes[1,0].set_title('Распределение годового дохода клиентов', fontsize=14, fontweight='bold')\n",
    "        axes[1,0].set_xlabel('Годовой доход')\n",
    "        axes[1,0].set_ylabel('Количество клиентов')\n",
    "    \n",
    "    # 5. Распределение суммы продаж\n",
    "    if 'SalesAmount' in df.columns:\n",
    "        axes[1,1].hist(df['SalesAmount'], bins=50, alpha=0.7, edgecolor='black', color='red')\n",
    "        axes[1,1].set_title('Распределение суммы продаж', fontsize=14, fontweight='bold')\n",
    "        axes[1,1].set_xlabel('Сумма продажи')\n",
    "        axes[1,1].set_ylabel('Количество')\n",
    "    \n",
    "    # 6. Топ продуктов по выручке\n",
    "    if 'ProductName' in df.columns:\n",
    "        top_products = df.groupby('ProductName')['SalesAmount'].sum().nlargest(10)\n",
    "        axes[1,2].barh(range(len(top_products)), top_products.values, color='purple', alpha=0.7)\n",
    "        axes[1,2].set_yticks(range(len(top_products)))\n",
    "        axes[1,2].set_yticklabels([label[:25] + '...' if len(label) > 25 else label \n",
    "                                 for label in top_products.index])\n",
    "        axes[1,2].set_title('Топ-10 продуктов по выручке', fontsize=14, fontweight='bold')\n",
    "        axes[1,2].set_xlabel('Выручка')\n",
    "    \n",
    "    plt.tight_layout()\n",
    "    plt.savefig('eda_analysis.png', dpi=300, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    \n",
    "    # Дополнительные интерактивные визуализации с Plotly\n",
    "    print(\"\\n📈 ИНТЕРАКТИВНЫЕ ВИЗУАЛИЗАЦИИ:\")\n",
    "    \n",
    "    if 'OrderDate' in df.columns and 'SalesAmount' in df.columns:\n",
    "        # Ежедневные продажи\n",
    "        daily_sales = df.groupby(df['OrderDate'].dt.date)['SalesAmount'].sum().reset_index()\n",
    "        fig1 = px.line(daily_sales, x='OrderDate', y='SalesAmount', \n",
    "                      title='📈 Динамика ежедневных продаж',\n",
    "                      labels={'OrderDate': 'Дата', 'SalesAmount': 'Выручка'})\n",
    "        fig1.show()\n",
    "    \n",
    "    if 'Region' in df.columns and 'SalesAmount' in df.columns:\n",
    "        # Продажи по регионам\n",
    "        region_performance = df.groupby('Region').agg({\n",
    "            'SalesAmount': 'sum',\n",
    "            'CustomerKey': 'nunique',\n",
    "            'OrderQuantity': 'sum'\n",
    "        }).reset_index()\n",
    "        \n",
    "        fig2 = px.bar(region_performance, x='Region', y='SalesAmount',\n",
    "                     title='🌍 Выручка по регионам',\n",
    "                     color='CustomerKey',\n",
    "                     labels={'SalesAmount': 'Выручка', 'CustomerKey': 'Количество клиентов'})\n",
    "        fig2.show()\n",
    "\n",
    "if cleaned_df is not None:\n",
    "    create_eda_visualizations(cleaned_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Создание дашбордов"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_dashboards(df):\n",
    "    \"\"\"Создание интерактивных дашбордов\"\"\"\n",
    "    \n",
    "    print(\"📊 СОЗДАНИЕ ДАШБОРДОВ\")\n",
    "    \n",
    "    # 1. Дашборд ключевых метрик\n",
    "    total_revenue = df['SalesAmount'].sum()\n",
    "    total_orders = df['SalesOrderNumber'].nunique()\n",
    "    total_customers = df['CustomerKey'].nunique()\n",
    "    avg_order_value = df.groupby('SalesOrderNumber')['SalesAmount'].sum().mean()\n",
    "    total_profit = df['Profit'].sum() if 'Profit' in df.columns else 0\n",
    "    \n",
    "    # Создаем дашборд с метриками\n",
    "    fig_metrics = go.Figure()\n",
    "    \n",
    "    fig_metrics.add_trace(go.Indicator(\n",
    "        mode=\"number\",\n",
    "        value=total_revenue,\n",
    "        title={\"text\": \"💰 Общая выручка\"},\n",
    "        number={'prefix': \"$\", \"valueformat\": \",.0f\"},\n",
    "        domain={'row': 0, 'column': 0}\n",
    "    ))\n",
    "    \n",
    "    fig_metrics.add_trace(go.Indicator(\n",
    "        mode=\"number\",\n",
    "        value=total_orders,\n",
    "        title={\"text\": \"📦 Всего заказов\"},\n",
    "        number={\"valueformat\": \",.0f\"},\n",
    "        domain={'row': 0, 'column': 1}\n",
    "    ))\n",
    "    \n",
    "    fig_metrics.add_trace(go.Indicator(\n",
    "        mode=\"number\",\n",
    "        value=total_customers,\n",
    "        title={\"text\": \"👥 Всего клиентов\"},\n",
    "        number={\"valueformat\": \",.0f\"},\n",
    "        domain={'row': 0, 'column': 2}\n",
    "    ))\n",
    "    \n",
    "    fig_metrics.add_trace(go.Indicator(\n",
    "        mode=\"number\",\n",
    "        value=avg_order_value,\n",
    "        title={\"text\": \"💵 Средний чек\"},\n",
    "        number={'prefix': \"$\", \"valueformat\": \",.0f\"},\n",
    "        domain={'row': 0, 'column': 3}\n",
    "    ))\n",
    "    \n",
    "    fig_metrics.update_layout(\n",
    "        grid={'rows': 1, 'columns': 4, 'pattern': \"independent\"},\n",
    "        template=\"plotly_white\",\n",
    "        height=300\n",
    "    )\n",
    "    \n",
    "    fig_metrics.show()\n",
    "    \n",
    "    # 2. Анализ продуктовой линейки\n",
    "    if 'Category' in df.columns and 'SubCategory' in df.columns:\n",
    "        product_analysis = df.groupby(['Category', 'SubCategory']).agg({\n",
    "            'SalesAmount': 'sum',\n",
    "            'Profit': 'sum',\n",
    "            'OrderQuantity': 'sum'\n",
    "        }).reset_index()\n",
    "        \n",
    "        fig_products = px.treemap(product_analysis,\n",
    "                                 path=['Category', 'SubCategory'],\n",
    "                                 values='SalesAmount',\n",
    "                                 color='Profit',\n",
    "                                 color_continuous_scale='RdYlGn',\n",
    "                                 title='📦 Дерево продуктов по выручке и прибыли')\n",
    "        fig_products.show()\n",
    "    \n",
    "    # 3. Анализ по демографии\n",
    "    if 'Gender' in df.columns and 'YearlyIncome' in df.columns:\n",
    "        demographic_analysis = df.groupby('Gender').agg({\n",
    "            'SalesAmount': 'sum',\n",
    "            'CustomerKey': 'nunique',\n",
    "            'YearlyIncome': 'mean'\n",
    "        }).reset_index()\n",
    "        \n",
    "        fig_demo = px.bar(demographic_analysis, x='Gender', y='SalesAmount',\n",
    "                         color='CustomerKey',\n",
    "                         title='👥 Анализ продаж по полу',\n",
    "                         labels={'SalesAmount': 'Выручка', 'CustomerKey': 'Количество клиентов'})\n",
    "        fig_demo.show()\n",
    "    \n",
    "    print(\"✅ Дашборды созданы и отображены\")\n",
    "\n",
    "if cleaned_df is not None:\n",
    "    create_dashboards(cleaned_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Извлечение ключевых инсайтов"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_insights(df):\n",
    "    \"\"\"Извлечение ключевых инсайтов\"\"\"\n",
    "    \n",
    "    print(\"💡 КЛЮЧЕВЫЕ ИНСАЙТЫ\")\n",
    "    print(\"=\" * 50)\n",
    "    \n",
    "    insights = []\n",
    "    \n",
    "    # 1. Общие метрики бизнеса\n",
    "    total_revenue = df['SalesAmount'].sum()\n",
    "    total_customers = df['CustomerKey'].nunique()\n",
    "    total_products = df['ProductKey'].nunique()\n",
    "    avg_order_value = df.groupby('SalesOrderNumber')['SalesAmount'].sum().mean()\n",
    "    \n",
    "    insights.append(f\"💰 Общая выручка: ${total_revenue:,.0f}\")\n",
    "    insights.append(f\"👥 Количество клиентов: {total_customers}\")\n",
    "    insights.append(f\"📦 Количество продуктов: {total_products}\")\n",
    "    insights.append(f\"📊 Средний чек: ${avg_order_value:,.0f}\")\n",
    "    \n",
    "    # 2. Анализ клиентской базы\n",
    "    customer_value = df.groupby('CustomerKey')['SalesAmount'].sum()\n",
    "    if len(customer_value) > 0:\n",
    "        top_20_percent = int(len(customer_value) * 0.2)\n",
    "        top_20_customers = customer_value.nlargest(top_20_percent).sum()\n",
    "        percent_top_20 = (top_20_customers / total_revenue) * 100\n",
    "        \n",
    "        insights.append(f\"🎯 Топ-20% клиентов приносят {percent_top_20:.1f}% выручки\")\n",
    "    \n",
    "    # 3. Анализ регионов\n",
    "    if 'Region' in df.columns:\n",
    "        best_region = df.groupby('Region')['SalesAmount'].sum().idxmax()\n",
    "        best_region_revenue = df.groupby('Region')['SalesAmount'].sum().max()\n",
    "        insights.append(f\"🌍 Лучший регион: {best_region} (${best_region_revenue:,.0f})\")\n",
    "    \n",
    "    # 4. Анализ продуктов\n",
    "    if 'Category' in df.columns:\n",
    "        best_category = df.groupby('Category')['SalesAmount'].sum().idxmax()\n",
    "        best_category_revenue = df.groupby('Category')['SalesAmount'].sum().max()\n",
    "        insights.append(f\"📦 Лучшая категория: {best_category} (${best_category_revenue:,.0f})\")\n",
    "    \n",
    "    # 5. Временной анализ\n",
    "    if 'OrderDate' in df.columns:\n",
    "        monthly_revenue = df.groupby(df['OrderDate'].dt.month)['SalesAmount'].sum()\n",
    "        if len(monthly_revenue) > 0:\n",
    "            best_month = monthly_revenue.idxmax()\n",
    "            worst_month = monthly_revenue.idxmin()\n",
    "            \n",
    "            month_names = {\n",
    "                1: 'Январь', 2: 'Февраль', 3: 'Март', 4: 'Апрель',\n",
    "                5: 'Май', 6: 'Июнь', 7: 'Июль', 8: 'Август',\n",
    "                9: 'Сентябрь', 10: 'Октябрь', 11: 'Ноябрь', 12: 'Декабрь'\n",
    "            }\n",
    "            \n",
    "            insights.append(f\"📈 Лучший месяц: {month_names.get(best_month, best_month)} (${monthly_revenue[best_month]:,.0f})\")\n",
    "            insights.append(f\"📉 Худший месяц: {month_names.get(worst_month, worst_month)} (${monthly_revenue[worst_month]:,.0f})\")\n",
    "    \n",
    "    # 6. Анализ прибыльности\n",
    "    if 'Profit' in df.columns:\n",
    "        total_profit = df['Profit'].sum()\n",
    "        avg_profit_margin = (total_profit / total_revenue) * 100\n",
    "        insights.append(f\"💵 Общая прибыль: ${total_profit:,.0f}\")\n",
    "        insights.append(f\"📊 Средняя маржа прибыли: {avg_profit_margin:.1f}%\")\n",
    "    \n",
    "    print(\"🎯 ОСНОВНЫЕ ИНСАЙТЫ:\")\n",
    "    for i, insight in enumerate(insights, 1):\n",
    "        print(f\"{i}. {insight}\")\n",
    "    \n",
    "    return insights\n",
    "\n",
    "if cleaned_df is not None:\n",
    "    insights = extract_insights(cleaned_df)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. RFM-анализ"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def perform_rfm_analysis(df):\n",
    "    \"\"\"Проведение RFM-анализа\"\"\"\n",
    "    \n",
    "    print(\"🎯 RFM-АНАЛИЗ\")\n",
    "    print(\"=\" * 30)\n",
    "    \n",
    "    # Расчет RFM метрик\n",
    "    snapshot_date = df['OrderDate'].max() + pd.Timedelta(days=1)\n",
    "    \n",
    "    rfm = df.groupby('CustomerKey').agg({\n",
    "        'OrderDate': lambda x: (snapshot_date - x.max()).days,  # Recency\n",
    "        'SalesOrderNumber': 'nunique',  # Frequency\n",
    "        'SalesAmount': 'sum'            # Monetary\n",
    "    }).reset_index()\n",
    "    \n",
    "    rfm.columns = ['CustomerKey', 'Recency', 'Frequency', 'Monetary']\n",
    "    \n",
    "    print(\"📊 Основные статистики RFM:\")\n",
    "    display(rfm[['Recency', 'Frequency', 'Monetary']].describe())\n",
    "    \n",
    "    # Создание RFM квантилей\n",
    "    rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5, 4, 3, 2, 1])\n",
    "    rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])\n",
    "    rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5])\n",
    "    \n",
    "    # RFM сегментация\n",
    "    rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)\n",
    "    \n",
    "    # Упрощенная сегментация\n",
    "    def assign_segment(row):\n",
    "        r, f, m = int(row['R_Score']), int(row['F_Score']), int(row['M_Score'])\n",
    "        \n",
    "        if r >=